# Generated by Django 3.2.12 on 2022-07-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachermodel',
            old_name='image_name',
            new_name='image',
        ),
    ]
