# Generated by Django 4.0.5 on 2022-07-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_image_name_teachermodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachermodel',
            name='subjects_taught',
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='subjects_taught',
            field=models.CharField(default=1, max_length=220),
            preserve_default=False,
        ),
    ]
